-- MySQL Workbench Synchronization
-- Generated: 2016-07-13 14:55
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Fredy

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `shippingweight`.`profile` 
ADD COLUMN `npwp` VARCHAR(64) NULL DEFAULT NULL AFTER `bio`,
ADD COLUMN `cp` VARCHAR(255) NULL DEFAULT NULL AFTER `npwp`,
ADD COLUMN `phone` VARCHAR(255) NULL DEFAULT NULL AFTER `cp`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
