-- MySQL Workbench Synchronization
-- Generated: 2017-01-06 11:25
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Fredy

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `shippingweight`.`container` 
ADD COLUMN `customer_id` VARCHAR(6) NULL DEFAULT NULL AFTER `transfer_id`,
ADD COLUMN `type` VARCHAR(8) NULL DEFAULT NULL AFTER `customer_id`,
ADD COLUMN `size` TINYINT(4) NULL DEFAULT NULL AFTER `type`,
ADD COLUMN `cargoStatus` VARCHAR(8) NULL DEFAULT NULL AFTER `size`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
