<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "certificate".
 *
 * @property integer $id
 * @property integer $shipper_id
 * @property integer $shipment_id
 * @property integer $weighing_id
 * @property string $date
 * @property double $grossmass
 * @property string $container_number
 * @property integer $created_by
 * @property integer $updated_by
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property \app\models\Shipper $shipper
 * @property \app\models\Shipment $shipment
 * @property \app\models\Weighing $weighing
 * @property string $aliasModel
 */
abstract class Certificate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'certificate';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['shipper_id', 'shipment_id', 'weighing_id'], 'integer'],
            [['date'], 'safe'],
            [['grossmass'], 'number'],
            [['container_number'], 'string', 'max' => 255],
            [['shipper_id'], 'exist', 'skipOnError' => true, 'targetClass' => Shipper::className(), 'targetAttribute' => ['shipper_id' => 'id']],
            [['shipment_id'], 'exist', 'skipOnError' => true, 'targetClass' => Shipment::className(), 'targetAttribute' => ['shipment_id' => 'id']],
            [['weighing_id'], 'exist', 'skipOnError' => true, 'targetClass' => Weighing::className(), 'targetAttribute' => ['weighing_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'shipper_id' => 'Shipper ID',
            'shipment_id' => 'Shipment ID',
            'weighing_id' => 'Weighing ID',
            'date' => 'Date',
            'grossmass' => 'Grossmass',
            'container_number' => 'Container Number',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getShipper()
    {
        return $this->hasOne(\app\models\Shipper::className(), ['id' => 'shipper_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getShipment()
    {
        return $this->hasOne(\app\models\Shipment::className(), ['id' => 'shipment_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWeighing()
    {
        return $this->hasOne(\app\models\Weighing::className(), ['id' => 'weighing_id']);
    }




}
