<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "customer".
 *
 * @property string $ID_CUSTOMER
 * @property string $CUSTOMER
 * @property string $CUSTOMER_TYPE
 * @property string $EMAIL
 * @property string $ADDR1
 * @property string $ADDR2
 * @property string $ADDR3
 * @property string $PHONE
 * @property string $AGENT
 * @property string $CONTACT_NAME
 * @property string $TAX_NO_NPWP
 * @property string $BLOCKED
 * @property string $aliasModel
 */
abstract class Customer extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const BLOCKED_YES = 'YES';
    const BLOCKED_NO = 'NO';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'customer';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['BLOCKED'], 'string'],
            [['ID_CUSTOMER'], 'string', 'max' => 6],
            [['CUSTOMER', 'ADDR2'], 'string', 'max' => 50],
            [['CUSTOMER_TYPE', 'ADDR3'], 'string', 'max' => 14],
            [['EMAIL'], 'string', 'max' => 39],
            [['ADDR1'], 'string', 'max' => 98],
            [['PHONE', 'TAX_NO_NPWP'], 'string', 'max' => 20],
            [['AGENT', 'CONTACT_NAME'], 'string', 'max' => 4],
            ['BLOCKED', 'in', 'range' => [
                    self::BLOCKED_YES,
                    self::BLOCKED_NO,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID_CUSTOMER' => 'Id  Customer',
            'CUSTOMER' => 'Customer',
            'CUSTOMER_TYPE' => 'Customer  Type',
            'EMAIL' => 'Email',
            'ADDR1' => 'Addr1',
            'ADDR2' => 'Addr2',
            'ADDR3' => 'Addr3',
            'PHONE' => 'Phone',
            'AGENT' => 'Agent',
            'CONTACT_NAME' => 'Contact  Name',
            'TAX_NO_NPWP' => 'Tax  No  Npwp',
            'BLOCKED' => 'Blocked',
        ];
    }




    /**
     * get column BLOCKED enum value label
     * @param string $value
     * @return string
     */
    public static function getBLOCKEDValueLabel($value){
        $labels = self::optsBLOCKED();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column BLOCKED ENUM value labels
     * @return array
     */
    public static function optsBLOCKED()
    {
        return [
            self::BLOCKED_YES => self::BLOCKED_YES,
            self::BLOCKED_NO => self::BLOCKED_NO,
        ];
    }

}
