<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "transfer".
 *
 * @property integer $id
 * @property string $time
 * @property string $from
 * @property integer $amount
 * @property integer $containerCount
 * @property string $containerList_all
 * @property string $containerList_confirmed
 * @property string $containerList_missed
 * @property string $note
 * @property integer $created_by
 * @property integer $updated_by
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property \app\models\Container[] $containers
 * @property string $aliasModel
 */
abstract class Transfer extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'transfer';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['time'], 'safe'],
            [['amount', 'containerCount'], 'integer'],
            [['containerList_all', 'containerList_confirmed', 'containerList_missed', 'note'], 'string'],
            [['from'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'time' => 'Time',
            'from' => 'From',
            'amount' => 'Amount',
            'containerCount' => 'Container Count',
            'containerList_all' => 'Container List All',
            'containerList_confirmed' => 'Container List Confirmed',
            'containerList_missed' => 'Container List Missed',
            'note' => 'Note',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContainers()
    {
        return $this->hasMany(\app\models\Container::className(), ['transfer_id' => 'id']);
    }




}
