<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "weighing".
 *
 * @property integer $id
 * @property string $container_number
 * @property integer $container_id
 * @property double $grossmass
 * @property string $job_order
 * @property string $stack_datetime
 * @property integer $emkl_id
 * @property double $gatein_grossmass
 * @property string $gatein_tracknumber
 * @property double $gateout_grossmass
 * @property string $gateout_tracknumber
 * @property integer $created_by
 * @property integer $updated_by
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class Weighing extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'weighing';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['container_number'], 'required'],
            [['container_id', 'emkl_id'], 'integer'],
            [['grossmass', 'gatein_grossmass', 'gateout_grossmass'], 'number'],
            [['stack_datetime'], 'safe'],
            [['container_number'], 'string', 'max' => 64],
            [['job_order', 'gatein_tracknumber', 'gateout_tracknumber'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'container_number' => 'Container Number',
            'container_id' => 'Container ID',
            'grossmass' => 'Grossmass',
            'job_order' => 'Job Order',
            'stack_datetime' => 'Stack Datetime',
            'emkl_id' => 'Emkl ID',
            'gatein_grossmass' => 'Gatein Grossmass',
            'gatein_tracknumber' => 'Gatein Tracknumber',
            'gateout_grossmass' => 'Gateout Grossmass',
            'gateout_tracknumber' => 'Gateout Tracknumber',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }




}
