<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "weighing".
 *
 * @property integer $id
 * @property string $container_number
 * @property string $date
 * @property double $grossmass
 * @property string $job_order
 * @property string $emkl_name
 * @property string $emkl_email
 * @property double $gatein_grossmass
 * @property string $gatein_trackNumber
 * @property double $gateout_grossmass
 * @property string $gateout_trackNumber
 * @property integer $created_by
 * @property integer $updated_by
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property \app\models\Certificate[] $certificates
 * @property string $aliasModel
 */
abstract class Weighing extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'weighing';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date'], 'safe'],
            [['grossmass', 'gatein_grossmass', 'gateout_grossmass'], 'number'],
            [['container_number', 'job_order', 'emkl_name', 'emkl_email', 'gatein_trackNumber', 'gateout_trackNumber'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'container_number' => 'Container Number',
            'date' => 'Date',
            'grossmass' => 'Grossmass',
            'job_order' => 'Job Order',
            'emkl_name' => 'Emkl Name',
            'emkl_email' => 'Emkl Email',
            'gatein_grossmass' => 'Gatein Grossmass',
            'gatein_trackNumber' => 'Gatein Track Number',
            'gateout_grossmass' => 'Gateout Grossmass',
            'gateout_trackNumber' => 'Gateout Track Number',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCertificates()
    {
        return $this->hasMany(\app\models\Certificate::className(), ['weighing_id' => 'id']);
    }




}
